#开发环境下的配置文件

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Newrun1019
  alioss:
    #地域节点
    endpoint: oss-cn-beijing.aliyuncs.com
    #bucket域名
    bucket-name: sky-itcast-20240908
    access-key-id: LTAI5t9Tykiy43uqKAbUs6Dm
    access-key-secret: sV8M8kz3KKZX0kN78gzWemFKUF4my9
  redis:
    host: localhost
    port: 6379
    password: Newrun1019
    database: 0
  wechat:
    appid: wx31cfad812adeb7e5
    secret: 9b607be24143ed72d9245f9bc7e15d62
#    #商户号
#    mchid:
#    #商户API整数的整数序列号
#    mch-serial-no:
#    #商户私钥文件
#    private-key-file-path:

